### ISSUE TITLE
aws/codebuild/standard:4.0 apt-get update -y fails reason: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid..

### ISSUE THREAD

**Issue by cd-vis** [aws/aws-codebuild-docker-images#419]
We are using the aws/codebuild/standard:4.0 in a build step in CodePipeline. The build fails at apt-get update -y exit status 100
Reason: 
Reading package lists...
95W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
96E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.

I found this issue, not sure if it is related but it's from  yesterday:
https://github.com/yarnpkg/yarn/issues/7866

**Comment by chrislove01** [comment]
Same here 

Added this to build spec to fix temporarily

```
    commands:
    #temp gpg error fix
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    #temp gpg error fix
    - apt-get update
```

**Comment by pdoerning** [comment]
Accordingly also effecting Version 3.0 and 5.0 as build specs are the same.

**Comment by thomaschaaf** [comment]
I created an AWS Support case: Case ID 7949152351

**Comment by repl-mike-roest** [comment]
Also effecting 2.0 as well

**Comment by subinataws** [comment]
Thanks for reporting the issue. We are working on updating these images.

As a workaround for CodeBuild standard image, please add the following command to your buildspec prior to any apt commands: 'curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -'. For Amazon Linux 2 images, add 'rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg'.

**Comment by tony-welch-vqd** [comment]
Same issue here using aws/codebuild/standard:4.0

**Comment by diegoclair** [comment]
Same here with standard 3.0 and 5.0 ..
I found this command and it work too: `apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com`
This command was mentioned here: https://github.com/yarnpkg/yarn/issues/7866
I don't know the exactly difference of the command `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`

**Comment by jordan314** [comment]
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -` worked for me but make sure it's before any apt-get commands, or apt-get will fail

**Comment by prasanthnarasimha** [comment]
Same issue. Using aws/codebuild/standard:4.0.
Resolved by adding the following command in buildspec before apt-get udpate
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`

**Comment by subinataws** [comment]
This should be resolved now. Let us know if you face any more issues.

**Comment by cd-vis** [comment]
I have removed the workaround and the build is successful.

**Comment by repl-mike-roest** [comment]
@subinataws 
I'm still getting failures using the standard:2.0 image
```
Reading package lists...
185 | W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
186 | E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
187

```

**Comment by subinataws** [comment]
@repl-mike-roest - standard:2.0 image is unfortunately no longer maintained. Could you please use one of the supported images: https://github.com/aws/aws-codebuild-docker-images#image-maintenance ?

Also, do note that only the maintained images are pre-cached on the build server on AWS cloud. Using standard:2.0, for example, would lead to long provisioning time as images will be downloaded from ECR every time.

**Comment by repl-mike-roest** [comment]
@subinataws thanks I've migrated our projects to 4.0 and they're working
