### ISSUE TITLE
Please Add Support for NodeJS 16

### ISSUE THREAD

**Issue by iamderrick** [aws/aws-codebuild-docker-images#490]
NodeJS 16 entered active long-term support very recently. Can you please add this runtime to the codebuild images?

**Comment by koooge** [comment]
👍 

workaround

```yaml
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
```

**Comment by nhaynes** [comment]
If the images use version managers under the hood, why limit the number of available runtime versions to a static set? Couldn't these images just be updated to pass specific versions on to the underlying version managers?

I imagine this could even be backwards compatible with the existing implementation and require a lot less ongoing maintenance of this repository. And a lot fewer workarounds from CodeBuild users.

Specific versions like this would pass straight thru to the nodejs `n` version manager:
```
phases:
  install:
    runtime-versions:
      nodejs: 16.13.1
```

and the image could still provide "supported" versions like 12, 14, 16:
```
phases:
  install:
    runtime-versions:
      nodejs: 14
```

**Comment by chunyang-sph** [comment]
waiting for support nodejs version 17

**Comment by critesjm** [comment]
bump! 16 has been in LTS for a while now...

**Comment by wilhen01** [comment]
Bump. Would be really good to have this...

**Comment by Chase-Dickerson** [comment]
They're getting closer, it seems. NodeJS 16 runtime is now [supported for Lambdas](https://aws.amazon.com/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/). However, it is [not yet available for codebuild](https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html).

**Comment by zoellner** [comment]
FYI, this seems to work now. docs still not updated but I tried it just now:
```
  install:
    runtime-versions:
      nodejs: 16
```

```


[Container] 2022/05/23 14:01:37 No commands found for phase name: install
--
7 | [Container] 2022/05/23 14:01:37 Processing environment variables
8 | [Container] 2022/05/23 14:01:37 Selecting 'nodejs' runtime version '16' based on manual selections...
9 | [Container] 2022/05/23 14:01:37 Running command echo "Installing Node.js version 16 ..."
10 | Installing Node.js version 16 ...
11 |  
12 | [Container] 2022/05/23 14:01:37 Running command n $NODE_16_VERSION
13 | copying : node/16.15.0
14 | installed : v16.15.0 (with npm 8.5.5)


```

**Comment by mneil** [comment]
Using a version manager isn't a viable solution to picking a version.

1. It increases already long build times / startup for an already slow service.
2. I'm paying for build times. See problem 1
3. Builds running in a VPC without an internet connection cannot pull and build new versions of node

AMI2022 isn't supported on codebuild. AMI2 is dead along with CentOS. Ubuntu images do not have latest software available even a year after it's been released. Please support your own products.

**Comment by DylanVann** [comment]
- Saw that Lambda supports Node 16 now, as of 10 days ago.
- Created PR to update Lamdba runtime, updated the CodeBuild runtime at the same time.
- PR runs on CodeBuild, uses Node 16 as mentioned https://github.com/aws/aws-codebuild-docker-images/issues/490#issuecomment-1134723620.
- Merged PR.
- Other PRs are now failing saying `Unknown runtime version named '16' of nodejs`.

So it seems that it isn't exactly fully rolled out. Very unfortunate it's only intermittently working, builds should be reproducible.

**Comment by DylanVann** [comment]
I also get `'nodejs16.x' runtime is not supported` as a Lambda error when downgrading just CodeBuild.

Is there some way to clear the pool of build machines we're using and just get ones that support Node 16?

**Comment by jpduckwo** [comment]
Tried in region ap-southeast-2... `nodejs: 16` isn't available yet

**Comment by arturoribessanz** [comment]
Yesterday morning it was available. At night and now it is not. Looks like they are having some issues updating the version.

**Comment by maheshsamudra** [comment]
> Yesterday morning it was available. At night and now it is not. Looks like they are having some issues updating the version.

Finally... it's good to know that they are working on it! I was checking https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html#linux-runtimes every week to see if it's available.

**Comment by brazilianbytes** [comment]
+1. It's a nice feature because Node 12 will go EOF at April 2022. AWS Lambda already have Node 16 available.

**Comment by jcuna** [comment]
This is pressing. We went through the deal of upgrading lambdas to 16 and we use codebuild to build our lambdas. Hope there's a fix soon.

**Comment by arturoribessanz** [comment]
> +1
> 
> workaround
> 
> ```yaml
> phases:
>   install:
>     runtime-versions:
>       nodejs: 14
>     commands:
>       - n 16
> ```

This workaround works well and does not add a lot of time to the build process.

**Comment by h5aaimtron** [comment]
nodejs: latest is defaulting back to v12.22.2 again. It was pulling 14+ for the last few months.

**Comment by jpduckwo** [comment]
> nodejs: latest is defaulting back to v12.22.2 again. It was pulling 14+ for the last few months.
I'm sceptical :) What region, and what is your build config?

**Comment by h5aaimtron** [comment]
A developer on my team played with some of the settings in dev without telling anyone. This can be closed.

**Comment by umertauheed** [comment]
> nodejs: latest is defaulting back to v12.22.2 again. It was pulling 14+ for the last few months.
having same issue for few days.



> > nodejs: latest is defaulting back to v12.22.2 again. It was pulling 14+ for the last few months.
> 
> I'm sceptical :) What region, and what is your build config?

region: Singapore

**Comment by HansFalkenberg-Visma** [comment]
It'd be great if codebuild could commit to getting the next LTS of node out earlier, like Lambda has (almost) promised.

> We recognize that customers have been waiting for some time for this runtime release. We hear your feedback and plan to release the next Node.js runtime version in a timelier manner.

https://aws.amazon.com/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/

**Comment by monigala** [comment]
> 👍
> 
> workaround
> 
> ```yaml
> phases:
>   install:
>     runtime-versions:
>       nodejs: 14
>     commands:
>       - n 16
> ```

After buildspec completes, the AWS Lambda displays Runtime `Node.js 14.x`. So its confusing. It's built with v16 but runs on v14?

**Comment by benton** [comment]
The production images built from this repo are referenced in the AWS CDK as, `aws_cdk.aws_codebuild.LinuxBuildImage`

a new version of the AWS CDK was released today that has [broken CDK pipelines][1] because it was not tested against Node 12 (or because Node 14 and/or 16 are not included in these images, depending your perspective).

Please release newer images with more recent, production-ready versions of NodeJS as soon as possible, thanks.


[1]:https://github.com/aws/aws-cdk/issues/20739

**Comment by alex-schwartzman-at-stratify** [comment]
NodeJS 14 LTS, AFAIK, is supported only until April 2023. When shall Amazon clients expect Node16 in CodeBuild images? Maybe May 2023?

**Comment by mbsimonovic** [comment]
us-east-1:
```
[Container] 2022/06/22 12:56:52 Unknown runtime version named '16' of nodejs. This build image has the following versions: 12, 14
10
```

**Comment by subinataws** [comment]
Addressed in https://github.com/aws/aws-codebuild-docker-images/releases/tag/22.06.30

**Comment by HansFalkenberg-Visma** [comment]
Thanks for getting this out. However, the documentation still says nodejs 14 is the latest available:
https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html
https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html

Also, anyone using CDK will have to wait just a little longer, if they don't want to use workarounds: https://github.com/aws/aws-cdk/issues/20960

**Comment by nandita121189** [comment]
I'm still getting the below error

```
 Phase context status code: YAML_FILE_ERROR Message: Unknown runtime version named '16' of nodejs. This build image has the following versions: 10, 12
```
The environment used for codebuild is as follows:

```
Environment: 
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:6.0
        ComputeType: BUILD_GENERAL1_SMALL
```

Buildspec versions needed
```

  install:
    runtime-versions:
      python: 3.8
      nodejs: 16
```

Region is us-west-2

Is it working for someone?

**Comment by maheshsamudra** [comment]
Nope. I moved back to Node 14 in standard5:0. This is not reliable yet.
What's up with AWS seriously?

**Comment by monigala** [comment]
We are using node16 in the "*us-east-1*" region. The attached AWS article
indicates it's available in all regions.

*cloudformation template*
Type: LINUX_CONTAINER
Image: aws/codebuild/standard:6.0
ComputeType: BUILD_GENERAL1_SMALL

*serverless.yml*
provider:
  name: aws
  runtime: nodejs16.x

An alternative is to use a custom Image that you build yourself. We used a
private ECR Image with node16 prior to this option being available.

*helpful articles*
https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-image.html

**Comment by nociza** [comment]
It seems that the aarch64 containers only support up to 12, which really should be updated by now. 
`Message: Unknown runtime version named '16' of nodejs. This build image has the following versions: 10, 12`

**Comment by cihan-paytrail** [comment]
I resolved this issue by updating the CodeBuild Linux image from the default 5.0 to 6.0. 

E.g. with Typescript & AWS CDK:

```
new PipelineProject(scope, `my-build`, {
  environment: {
    buildImage: LinuxBuildImage.STANDARD_6_0,
  }
});
```

**Comment by ilyakonrad** [comment]
Year later it is still not supported?

**Comment by dls314** [comment]
> Year later it is still not supported?

Supported https://github.com/aws/aws-codebuild-docker-images/issues/490#issuecomment-1172712676

**Comment by ilyakonrad** [comment]
> > Year later it is still not supported?
> 
> Supported [#490 (comment)](https://github.com/aws/aws-codebuild-docker-images/issues/490#issuecomment-1172712676)

I mean `nodejs: 16` didn't work today, should I use the full version name?

**Comment by thiagosanches** [comment]
It's not working yet:
![image](https://user-images.githubusercontent.com/5191469/199061625-28e9d1d8-3a0c-4b0d-a599-0b5cebabf6ef.png)

**Comment by N1kell** [comment]
> It's not working yet: ![image](https://user-images.githubusercontent.com/5191469/199061625-28e9d1d8-3a0c-4b0d-a599-0b5cebabf6ef.png)

For me switching "Current environment image" to
aws/codebuild/standard:6.0
solved the issue

**Comment by GabrielDelepine** [comment]
The available runtimes are listed in the definition of the docker images provided by CodeBuild

https://docs.aws.amazon.com/en_us/codebuild/latest/userguide/build-env-ref-available.html

For instance

- `aws/codebuild/amazonlinux2-aarch64-standard:1.0` supports nodejs 8, 10 and 12
- `aws/codebuild/amazonlinux2-aarch64-standard:2.0` supports nodejs 10 and 12

- `aws/codebuild/amazonlinux2-x86_64-standard:3.0` supports nodejs 10 and 12
- `aws/codebuild/amazonlinux2-x86_64-standard:4.0` supports nodejs 16

- `aws/codebuild/standard:6.0` supports nodejs 16

Personnaly, I am locking for Node 18

**Comment by joebowbeer** [comment]
@koooge wrote:

> workaround
> 
> ```yaml
> phases:
>   install:
>     runtime-versions:
>       nodejs: 14
>     commands:
>       - n 16
> ```

In case it's not clear, this same technique can be used to install nodejs 18 on `aws/codebuild/standard:5.0`

```yaml
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 18
```
