### ISSUE TITLE
Local Builds not working for Mac

### ISSUE THREAD

**Issue by peterfox** [aws/aws-codebuild-docker-images#61]
I've been trying to follow the example from the [AWS article](https://aws.amazon.com/blogs/devops/announcing-local-build-support-for-aws-codebuild/) with no success.

Every time I run the build the buildspec.yml file can't be found.

I'm using Docker version 18.03.1-ce, build 9ee9f40 for Mac OS.

**Comment by AWSstangers** [comment]
Please verify you are using the absolute path for your source directory. This value will vary from the article example since you are on a different operating system.  

Example on a Mac: (Note: the /home/ was changed to /Users/)

     docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/java:openjdk-8" -e "ARTIFACTS=/Users/ec2-user/environment/artifacts" -e "SOURCE=/Users/ec2-user/environment/sample-web-app" amazon/aws-codebuild-local

**Comment by peterfox** [comment]
Thank you, the example now works for me. I still have some issues with using the aws/codebuild/docker:17.09.0 image. Is it possible to use the local build setup to create docker images?

**Comment by subinataws** [comment]
Local agent doesn't support building Docker images locally today. We'll get that fixed in the next update. Marking this feature request.

**Comment by georgealton** [comment]
I'm also having issues running locally on OSX

Docker & OSX Versions
```
macOS: version 10.13.4 (build: 17E199)
Docker.app: version: 18.03.1-ce-mac65 (dd2831d4b7421cf559a0881cc7a5fdebeb8c2b98)
Local time: Sat 12 May 2018 10:38:46 BST
UTC:        Sat 12 May 2018 09:38:46 UTC
```

building the python 3.6.5 image
```bash
docker build --quiet -t aws/codebuild/python:3.6.5 https://github.com/aws/aws-codebuild-docker-images.git#master:ubuntu/python/3.6.5
sha256:d8d5c4018405f160475bf6a3e2d141474159134bf9f1397f462d92fedc24d1b3
```

pulling the codebuild agent
```bash
docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false
Pull (1 of 1): amazon/aws-codebuild-local:latest@sha256:004d34c4e908d074edb205b2299cead4ecf30adf284ea7a50912da817e32150f
sha256:004d34c4e908d074edb205b2299cead4ecf30adf284ea7a50912da817e32150f: Pulling from amazon/aws-codebuild-local
Digest: sha256:004d34c4e908d074edb205b2299cead4ecf30adf284ea7a50912da817e32150f
Status: Image is up to date for amazon/aws-codebuild-local@sha256:004d34c4e908d074edb205b2299cead4ecf30adf284ea7a50912da817e32150f
Tagging amazon/aws-codebuild-local@sha256:004d34c4e908d074edb205b2299cead4ecf30adf284ea7a50912da817e32150f as amazon/aws-codebuild-local:latest
```

running the container ( the attempt below includes `--privileged` option )
```bash
mkdir -p artifacts
docker run -it --privileged -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/python:3.6.5" -e "ARTIFACTS=$(pwd)/artifacts" -e "SOURCE=$(pwd)" amazon/aws-codebuild-local
Removing network agentresources_default
WARNING: Network agentresources_default not found.
Removing volume agentresources_user_volume
WARNING: Volume agentresources_user_volume not found.
Removing volume agentresources_source_volume
WARNING: Volume agentresources_source_volume not found.
Creating network "agentresources_default" with the default driver
Creating volume "agentresources_user_volume" with local driver
Creating volume "agentresources_source_volume" with local driver
Creating agentresources_agent_1 ...
Creating agentresources_agent_1 ... done
Creating agentresources_build_1 ...
Creating agentresources_build_1 ... done
Attaching to agentresources_agent_1, agentresources_build_1
build_1  | time="2018-05-12T09:20:20.017010338Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
build_1  | time="2018-05-12T09:20:20.017170247Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
build_1  | time="2018-05-12T09:20:20.018029660Z" level=info msg="libcontainerd: new containerd process, pid: 21"
build_1  | time="2018-05-12T09:20:21.019703574Z" level=warning msg="failed to rename /var/lib/docker/tmp for background deletion: rename /var/lib/docker/tmp /var/lib/docker/tmp-old: no such file or directory. Deleting synchronously"
build_1  | Error starting daemon: couldn't create plugin manager: error setting plugin manager root to private: operation not permitted
build_1  | Timed out trying to connect to internal docker host.
agentresources_build_1 exited with code 1
```

Seems like there is an issue with the docker.sock

**Comment by peterfox** [comment]
@georgealton You need to build the local image "aws/codebuild/python:3.6.5" without the 

> ENTRYPOINT [“dockerd-entrypoint.sh”]

 line in the docker file for that image. After you do so it won't have that error.

**Comment by georgealton** [comment]
thanks @peterfox -- missed that part 😳 

my command was performing the build directly from github, so I didn't create a local copy of the repo. I've tried to remove the ENTRYPOINT at runtime, but didn't have any success. But modifying the Dockerfile works! :)

**Comment by subinataws** [comment]
Fixed with latest agent release. Get the latest version from DockerHub. docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false

SHA: 138c94d4663b9e813005d043e27004c5af189bf5903205444b2a431df3c1be1b

**Comment by dieterrosch** [comment]
FYI,

The fix proposed by peterfox for the error:
_**msg="could not change group /var/run/docker.sock to docker: group docker not found"**_
is not fixed in the Dockerfile at **aws-codebuild-docker-images/ubuntu/standard/2.0/Dockerfile** yet.

So to get docker images to work, you need to put --privileged into the docker command which is inside codebuild_build.sh file, and then you also need to comment out the ENTRYPOINT ["dockerd-entrypoint.sh"] command inside "aws-codebuild-docker-images/ubuntu/standard/2.0/Dockerfile"
